package Try_Catch

/*fun some(array: Array<Any>){
    try{
        println("try top(),,,")

        val data: Int = array[0] as Int

        val data2: String = array[1] as String

        val temp: Int = data.toInt()
    }
    catch (e: ClassCastException){
        println("ClassCastException catch,,")
    }
    catch (e: Exception){
        println("Exception catch,, ${e.toString()}")
    }
    catch (e: ArrayIndexOutOfBoundsException){
        println("ArrayIndexOutOfBoundsException catch,,,")
    }
}

fun main(args: Array<String>) {
    //캐스팅 예외
    val mainData1 = arrayOf("1", 2, "3")
    some(mainData1)

    //배열 범위 오버
    val mainData2 = arrayOf(4,"5")
    some(mainData2)

    //숫자 타입 예외
    val mainData3 = arrayOf(1,"2", "hello")
    some(mainData3)

    val temp = Integer.parseInt(mainData1[0] as String?)

    println("$temp")
}*/